### ISSUE TITLE
Sungrow SH5K: Value not available | 

### ISSUE THREAD

**Issue by HiiDaddy** [mvandersteen/ha-sungrow#4]
Hi mate,

Are you still supporting and/or still using this addon?

I have some questions if you have some time.

Using Sungrow SH5K

I have the following faults:

Logger: custom_components.sungrow.sensor
Source: custom_components/sungrow/sensor.py:340
Integration: Sungrow ([documentation](https://github.com/mvandersteen/ha-sungrow), [issues](https://github.com/mvandersteen/ha-sungrow/issues))
First occurred: 1:32:22 PM (16 occurrences)
Last logged: 1:33:22 PM

Sensor lookup value is not available in data array: total_battery_charge_energy_from_pv
Sensor lookup value is not available in data array: daily_battery_discharge_energy
Sensor lookup value is not available in data array: total_battery_discharge_energy
Sensor lookup value is not available in data array: daily_export_power_from_pv
Sensor lookup value is not available in data array: total_export_power_from_pv

AND
<Not sure if this is relevant>

Logger: homeassistant.components.sensor
Source: custom_components/sungrow/sensor.py:269
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 1:32:20 PM (1 occurrences)
Last logged: 1:32:20 PM

Error while setting up sungrow platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/sungrow/sensor.py", line 269, in async_setup_platform
    ip_address=config[CONF_IP_ADDRESS],
KeyError: 'ip_address'

**Sensor.py: ln 264-275**
---------------------------------------------------------------------
    """Set up the Jemena Outlook sensor."""

    sungrowclient = await hass.async_add_executor_job(
        partial(
            SungrowInverter,
            ip_address=config[CONF_IP_ADDRESS],
            port=config[CONF_PORT],
            slave=config[CONF_SLAVE],
            retries=3,
            timeout=int(config[CONF_TIMEOUT]),
        )
    )
----------------------------------------------------------------------

AND
<this one provides data in dashboard but does not integrate into energy dashboard>

Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:259
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 1:35:10 PM (5 occurrences)
Last logged: 1:35:10 PM

sensor.sungrow_pv_array_1_energy_generation has unit W which is unsupported for device_class energy
sensor.sungrow_pv_array_2_energy_generation has unit W which is unsupported for device_class energy
sensor.sungrow_current_load_power has unit W which is unsupported for device_class energy
sensor.sungrow_current_export_power has unit W which is unsupported for device_class energy
sensor.sungrow_energy_generation has unit W which is unsupported for device_class energy

**Comment by flare04** [comment]
Did you ever get this to work ?

**Comment by ph0nebooth** [comment]
I'm facing issues with the Sungrow SG5K-D. 

```

2023/07/10 11:52:28 INFO: Connecting to SunGrow...
2023/07/10 11:52:29 INFO: Found SunGrow 1 devices
Error: identifier rejected
Usage:
  GoSungrow mqtt run [flags]

```
